# file|search|replace|check
# cmd checks optional

CMD | update from configured repositories | "${WYN_HOME}/libs/update.sh" -y

CMD | show suspicious files, accounts, software, listeners, and processes | "${WYN_HOME}/wyn" checklist
