if ! declare -p KNOWN_GOOD &>/dev/null; then
    readonly -a KNOWN_GOOD=(
        /usr/bin/passwd
        /usr/bin/chsh
        /usr/bin/chfn
        /usr/bin/crontab
        /usr/bin/su
        /usr/bin/sudo
        /usr/bin/pkexec
        /usr/bin/newgrp
        /usr/bin/gpasswd
        /usr/bin/expiry
        /usr/sbin/pppd
        /bin/mount
        /bin/umount
        /bin/fusermount
        /usr/bin/mount
        /usr/bin/umount
        /usr/bin/chage
        /usr/bin/ssh-agent
        /usr/sbin/unix_chkpwd
        /usr/lib/dbus-1.0/dbus-daemon-launch-helper
        /usr/lib/openssh/ssh-keysign
        /usr/lib/policykit-1/polkit-agent-helper-1
    )
fi
